Make Call Share section
baza-trainee/13-zbir pull request #21
Opened 2024-06-18 19:41 UTC by NazarSak

2024-06-19 18:57 UTC, NataliaMahera requested changes
1. Видалити кнопку в файлі CallShare.tsx і зробити імпорт кнопки reusableButton, вона під капотом має тег button, додати всі потрібні атрибути.
2. В цьому ж файлі видалити імпорт реакту, він не використовується, потім при деплої можуть бути проблеми.
3. Поправити в стилях адаптиву контейнери.
4. Назви класів в стилях бажано писати з малої літери.

2024-06-20 14:58 UTC, NataliaMahera requested changes, later dismissed
Виправити падінги контейнера на 1440px

2024-06-20 18:04 UTC, mitskelevychp approved these changes

2024-06-20 18:07 UTC, baza-trainee approved these changes

2024-06-20 18:07 UTC, merged